### YamlMime:ManagedReference
items:
- uid: Neutronium.BuildingBlocks.Application.Navigation.ISubNavigator
  commentId: T:Neutronium.BuildingBlocks.Application.Navigation.ISubNavigator
  id: ISubNavigator
  parent: Neutronium.BuildingBlocks.Application.Navigation
  children:
  - Neutronium.BuildingBlocks.Application.Navigation.ISubNavigator.Child
  - Neutronium.BuildingBlocks.Application.Navigation.ISubNavigator.ChildName
  langs:
  - csharp
  - vb
  name: ISubNavigator
  nameWithType: ISubNavigator
  fullName: Neutronium.BuildingBlocks.Application.Navigation.ISubNavigator
  type: Interface
  source:
    remote:
      path: Neutronium.BuildingBlocks.Application/Navigation/Interface/ISubNavigator.cs
      branch: master
      repo: https://github.com/NeutroniumCore/ViewModel.Tools.git
    id: ISubNavigator
    path: ../Neutronium.BuildingBlocks.Application/Navigation/Interface/ISubNavigator.cs
    startLine: 5
  assemblies:
  - Neutronium.BuildingBlocks.Application
  namespace: Neutronium.BuildingBlocks.Application.Navigation
  summary: "\nManage relative navigation within ViewModel\n"
  example: []
  syntax:
    content: public interface ISubNavigator
    content.vb: Public Interface ISubNavigator
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Neutronium.BuildingBlocks.Application.Navigation.ISubNavigator.ChildName
  commentId: P:Neutronium.BuildingBlocks.Application.Navigation.ISubNavigator.ChildName
  id: ChildName
  parent: Neutronium.BuildingBlocks.Application.Navigation.ISubNavigator
  langs:
  - csharp
  - vb
  name: ChildName
  nameWithType: ISubNavigator.ChildName
  fullName: Neutronium.BuildingBlocks.Application.Navigation.ISubNavigator.ChildName
  type: Property
  source:
    remote:
      path: Neutronium.BuildingBlocks.Application/Navigation/Interface/ISubNavigator.cs
      branch: master
      repo: https://github.com/NeutroniumCore/ViewModel.Tools.git
    id: ChildName
    path: ../Neutronium.BuildingBlocks.Application/Navigation/Interface/ISubNavigator.cs
    startLine: 10
  assemblies:
  - Neutronium.BuildingBlocks.Application
  namespace: Neutronium.BuildingBlocks.Application.Navigation
  summary: "\nRelative Name of Child\n"
  example: []
  syntax:
    content: string ChildName { get; }
    parameters: []
    return:
      type: System.String
    content.vb: ReadOnly Property ChildName As String
  overload: Neutronium.BuildingBlocks.Application.Navigation.ISubNavigator.ChildName*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
- uid: Neutronium.BuildingBlocks.Application.Navigation.ISubNavigator.Child
  commentId: P:Neutronium.BuildingBlocks.Application.Navigation.ISubNavigator.Child
  id: Child
  parent: Neutronium.BuildingBlocks.Application.Navigation.ISubNavigator
  langs:
  - csharp
  - vb
  name: Child
  nameWithType: ISubNavigator.Child
  fullName: Neutronium.BuildingBlocks.Application.Navigation.ISubNavigator.Child
  type: Property
  source:
    remote:
      path: Neutronium.BuildingBlocks.Application/Navigation/Interface/ISubNavigator.cs
      branch: master
      repo: https://github.com/NeutroniumCore/ViewModel.Tools.git
    id: Child
    path: ../Neutronium.BuildingBlocks.Application/Navigation/Interface/ISubNavigator.cs
    startLine: 15
  assemblies:
  - Neutronium.BuildingBlocks.Application
  namespace: Neutronium.BuildingBlocks.Application.Navigation
  summary: "\nChild\n"
  example: []
  syntax:
    content: ISubNavigator Child { get; }
    parameters: []
    return:
      type: Neutronium.BuildingBlocks.Application.Navigation.ISubNavigator
    content.vb: ReadOnly Property Child As ISubNavigator
  overload: Neutronium.BuildingBlocks.Application.Navigation.ISubNavigator.Child*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
references:
- uid: Neutronium.BuildingBlocks.Application.Navigation
  commentId: N:Neutronium.BuildingBlocks.Application.Navigation
  name: Neutronium.BuildingBlocks.Application.Navigation
  nameWithType: Neutronium.BuildingBlocks.Application.Navigation
  fullName: Neutronium.BuildingBlocks.Application.Navigation
- uid: Neutronium.BuildingBlocks.Application.Navigation.ISubNavigator.ChildName*
  commentId: Overload:Neutronium.BuildingBlocks.Application.Navigation.ISubNavigator.ChildName
  name: ChildName
  nameWithType: ISubNavigator.ChildName
  fullName: Neutronium.BuildingBlocks.Application.Navigation.ISubNavigator.ChildName
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Neutronium.BuildingBlocks.Application.Navigation.ISubNavigator.Child*
  commentId: Overload:Neutronium.BuildingBlocks.Application.Navigation.ISubNavigator.Child
  name: Child
  nameWithType: ISubNavigator.Child
  fullName: Neutronium.BuildingBlocks.Application.Navigation.ISubNavigator.Child
- uid: Neutronium.BuildingBlocks.Application.Navigation.ISubNavigator
  commentId: T:Neutronium.BuildingBlocks.Application.Navigation.ISubNavigator
  parent: Neutronium.BuildingBlocks.Application.Navigation
  name: ISubNavigator
  nameWithType: ISubNavigator
  fullName: Neutronium.BuildingBlocks.Application.Navigation.ISubNavigator
