### YamlMime:ManagedReference
items:
- uid: Neutronium.BuildingBlocks.Application.Navigation.IRouterSolver
  commentId: T:Neutronium.BuildingBlocks.Application.Navigation.IRouterSolver
  id: IRouterSolver
  parent: Neutronium.BuildingBlocks.Application.Navigation
  children:
  - Neutronium.BuildingBlocks.Application.Navigation.IRouterSolver.SolveRoute(System.Object)
  - Neutronium.BuildingBlocks.Application.Navigation.IRouterSolver.SolveRoute``1
  - Neutronium.BuildingBlocks.Application.Navigation.IRouterSolver.SolveType(System.String)
  langs:
  - csharp
  - vb
  name: IRouterSolver
  nameWithType: IRouterSolver
  fullName: Neutronium.BuildingBlocks.Application.Navigation.IRouterSolver
  type: Interface
  source:
    remote:
      path: Neutronium.BuildingBlocks.Application/Navigation/IRouterSolver.cs
      branch: master
      repo: https://github.com/NeutroniumCore/Neutronium.BuildingBlocks.git
    id: IRouterSolver
    path: ../Neutronium.BuildingBlocks.Application/Navigation/IRouterSolver.cs
    startLine: 7
  assemblies:
  - Neutronium.BuildingBlocks.Application
  namespace: Neutronium.BuildingBlocks.Application.Navigation
  summary: "\nRouting configuration associating viewModels and route\n"
  example: []
  syntax:
    content: public interface IRouterSolver
    content.vb: Public Interface IRouterSolver
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Neutronium.BuildingBlocks.Application.Navigation.IRouterSolver.SolveRoute(System.Object)
  commentId: M:Neutronium.BuildingBlocks.Application.Navigation.IRouterSolver.SolveRoute(System.Object)
  id: SolveRoute(System.Object)
  parent: Neutronium.BuildingBlocks.Application.Navigation.IRouterSolver
  langs:
  - csharp
  - vb
  name: SolveRoute(Object)
  nameWithType: IRouterSolver.SolveRoute(Object)
  fullName: Neutronium.BuildingBlocks.Application.Navigation.IRouterSolver.SolveRoute(System.Object)
  type: Method
  source:
    remote:
      path: Neutronium.BuildingBlocks.Application/Navigation/IRouterSolver.cs
      branch: master
      repo: https://github.com/NeutroniumCore/Neutronium.BuildingBlocks.git
    id: SolveRoute
    path: ../Neutronium.BuildingBlocks.Application/Navigation/IRouterSolver.cs
    startLine: 16
  assemblies:
  - Neutronium.BuildingBlocks.Application
  namespace: Neutronium.BuildingBlocks.Application.Navigation
  summary: "\nFind route associated with the viewModel\n"
  example: []
  syntax:
    content: string SolveRoute(object viewModel)
    parameters:
    - id: viewModel
      type: System.Object
      description: ''
    return:
      type: System.String
      description: "\nThe corresponding route\n"
    content.vb: Function SolveRoute(viewModel As Object) As String
  overload: Neutronium.BuildingBlocks.Application.Navigation.IRouterSolver.SolveRoute*
- uid: Neutronium.BuildingBlocks.Application.Navigation.IRouterSolver.SolveRoute``1
  commentId: M:Neutronium.BuildingBlocks.Application.Navigation.IRouterSolver.SolveRoute``1
  id: SolveRoute``1
  parent: Neutronium.BuildingBlocks.Application.Navigation.IRouterSolver
  langs:
  - csharp
  - vb
  name: SolveRoute<T>()
  nameWithType: IRouterSolver.SolveRoute<T>()
  fullName: Neutronium.BuildingBlocks.Application.Navigation.IRouterSolver.SolveRoute<T>()
  type: Method
  source:
    remote:
      path: Neutronium.BuildingBlocks.Application/Navigation/IRouterSolver.cs
      branch: master
      repo: https://github.com/NeutroniumCore/Neutronium.BuildingBlocks.git
    id: SolveRoute
    path: ../Neutronium.BuildingBlocks.Application/Navigation/IRouterSolver.cs
    startLine: 25
  assemblies:
  - Neutronium.BuildingBlocks.Application
  namespace: Neutronium.BuildingBlocks.Application.Navigation
  summary: "\nFind route associated with the provided type\n"
  example: []
  syntax:
    content: string SolveRoute<T>()
    typeParameters:
    - id: T
      description: ''
    return:
      type: System.String
      description: "\nThe corresponding route\n"
    content.vb: Function SolveRoute(Of T) As String
  overload: Neutronium.BuildingBlocks.Application.Navigation.IRouterSolver.SolveRoute*
  nameWithType.vb: IRouterSolver.SolveRoute(Of T)()
  fullName.vb: Neutronium.BuildingBlocks.Application.Navigation.IRouterSolver.SolveRoute(Of T)()
  name.vb: SolveRoute(Of T)()
- uid: Neutronium.BuildingBlocks.Application.Navigation.IRouterSolver.SolveType(System.String)
  commentId: M:Neutronium.BuildingBlocks.Application.Navigation.IRouterSolver.SolveType(System.String)
  id: SolveType(System.String)
  parent: Neutronium.BuildingBlocks.Application.Navigation.IRouterSolver
  langs:
  - csharp
  - vb
  name: SolveType(String)
  nameWithType: IRouterSolver.SolveType(String)
  fullName: Neutronium.BuildingBlocks.Application.Navigation.IRouterSolver.SolveType(System.String)
  type: Method
  source:
    remote:
      path: Neutronium.BuildingBlocks.Application/Navigation/IRouterSolver.cs
      branch: master
      repo: https://github.com/NeutroniumCore/Neutronium.BuildingBlocks.git
    id: SolveType
    path: ../Neutronium.BuildingBlocks.Application/Navigation/IRouterSolver.cs
    startLine: 34
  assemblies:
  - Neutronium.BuildingBlocks.Application
  namespace: Neutronium.BuildingBlocks.Application.Navigation
  summary: "\nFind the viewModel type associated with the corresponding route\n"
  example: []
  syntax:
    content: Type SolveType(string route)
    parameters:
    - id: route
      type: System.String
      description: ''
    return:
      type: System.Type
      description: "\nThe corresponding\n"
    content.vb: Function SolveType(route As String) As Type
  overload: Neutronium.BuildingBlocks.Application.Navigation.IRouterSolver.SolveType*
references:
- uid: Neutronium.BuildingBlocks.Application.Navigation
  commentId: N:Neutronium.BuildingBlocks.Application.Navigation
  name: Neutronium.BuildingBlocks.Application.Navigation
  nameWithType: Neutronium.BuildingBlocks.Application.Navigation
  fullName: Neutronium.BuildingBlocks.Application.Navigation
- uid: Neutronium.BuildingBlocks.Application.Navigation.IRouterSolver.SolveRoute*
  commentId: Overload:Neutronium.BuildingBlocks.Application.Navigation.IRouterSolver.SolveRoute
  name: SolveRoute
  nameWithType: IRouterSolver.SolveRoute
  fullName: Neutronium.BuildingBlocks.Application.Navigation.IRouterSolver.SolveRoute
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Neutronium.BuildingBlocks.Application.Navigation.IRouterSolver.SolveType*
  commentId: Overload:Neutronium.BuildingBlocks.Application.Navigation.IRouterSolver.SolveType
  name: SolveType
  nameWithType: IRouterSolver.SolveType
  fullName: Neutronium.BuildingBlocks.Application.Navigation.IRouterSolver.SolveType
- uid: System.Type
  commentId: T:System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
