### YamlMime:ManagedReference
items:
- uid: Neutronium.BuildingBlocks.Application.ViewModels.ApplicationInformation
  commentId: T:Neutronium.BuildingBlocks.Application.ViewModels.ApplicationInformation
  id: ApplicationInformation
  parent: Neutronium.BuildingBlocks.Application.ViewModels
  children:
  - Neutronium.BuildingBlocks.Application.ViewModels.ApplicationInformation.#ctor(System.String,System.String)
  - Neutronium.BuildingBlocks.Application.ViewModels.ApplicationInformation.MadeBy
  - Neutronium.BuildingBlocks.Application.ViewModels.ApplicationInformation.Name
  - Neutronium.BuildingBlocks.Application.ViewModels.ApplicationInformation.Version
  - Neutronium.BuildingBlocks.Application.ViewModels.ApplicationInformation.Year
  langs:
  - csharp
  - vb
  name: ApplicationInformation
  nameWithType: ApplicationInformation
  fullName: Neutronium.BuildingBlocks.Application.ViewModels.ApplicationInformation
  type: Class
  source:
    remote:
      path: Neutronium.BuildingBlocks.Application/ViewModels/ApplicationInformation.cs
      branch: master
      repo: https://github.com/NeutroniumCore/Neutronium.BuildingBlocks.git
    id: ApplicationInformation
    path: ../Neutronium.BuildingBlocks.Application/ViewModels/ApplicationInformation.cs
    startLine: 8
  assemblies:
  - Neutronium.BuildingBlocks.Application
  namespace: Neutronium.BuildingBlocks.Application.ViewModels
  summary: "\nApplication MetaData \n"
  example: []
  syntax:
    content: public class ApplicationInformation
    content.vb: Public Class ApplicationInformation
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Neutronium.BuildingBlocks.Application.ViewModels.ApplicationInformation.#ctor(System.String,System.String)
  commentId: M:Neutronium.BuildingBlocks.Application.ViewModels.ApplicationInformation.#ctor(System.String,System.String)
  id: '#ctor(System.String,System.String)'
  parent: Neutronium.BuildingBlocks.Application.ViewModels.ApplicationInformation
  langs:
  - csharp
  - vb
  name: ApplicationInformation(String, String)
  nameWithType: ApplicationInformation.ApplicationInformation(String, String)
  fullName: Neutronium.BuildingBlocks.Application.ViewModels.ApplicationInformation.ApplicationInformation(System.String, System.String)
  type: Constructor
  source:
    remote:
      path: Neutronium.BuildingBlocks.Application/ViewModels/ApplicationInformation.cs
      branch: master
      repo: https://github.com/NeutroniumCore/Neutronium.BuildingBlocks.git
    id: .ctor
    path: ../Neutronium.BuildingBlocks.Application/ViewModels/ApplicationInformation.cs
    startLine: 10
  assemblies:
  - Neutronium.BuildingBlocks.Application
  namespace: Neutronium.BuildingBlocks.Application.ViewModels
  syntax:
    content: public ApplicationInformation(string name, string madeBy)
    parameters:
    - id: name
      type: System.String
    - id: madeBy
      type: System.String
    content.vb: Public Sub New(name As String, madeBy As String)
  overload: Neutronium.BuildingBlocks.Application.ViewModels.ApplicationInformation.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Neutronium.BuildingBlocks.Application.ViewModels.ApplicationInformation.Name
  commentId: P:Neutronium.BuildingBlocks.Application.ViewModels.ApplicationInformation.Name
  id: Name
  parent: Neutronium.BuildingBlocks.Application.ViewModels.ApplicationInformation
  langs:
  - csharp
  - vb
  name: Name
  nameWithType: ApplicationInformation.Name
  fullName: Neutronium.BuildingBlocks.Application.ViewModels.ApplicationInformation.Name
  type: Property
  source:
    remote:
      path: Neutronium.BuildingBlocks.Application/ViewModels/ApplicationInformation.cs
      branch: master
      repo: https://github.com/NeutroniumCore/Neutronium.BuildingBlocks.git
    id: Name
    path: ../Neutronium.BuildingBlocks.Application/ViewModels/ApplicationInformation.cs
    startLine: 21
  assemblies:
  - Neutronium.BuildingBlocks.Application
  namespace: Neutronium.BuildingBlocks.Application.ViewModels
  summary: "\nApplication name\n"
  example: []
  syntax:
    content: public string Name { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public ReadOnly Property Name As String
  overload: Neutronium.BuildingBlocks.Application.ViewModels.ApplicationInformation.Name*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Neutronium.BuildingBlocks.Application.ViewModels.ApplicationInformation.Version
  commentId: P:Neutronium.BuildingBlocks.Application.ViewModels.ApplicationInformation.Version
  id: Version
  parent: Neutronium.BuildingBlocks.Application.ViewModels.ApplicationInformation
  langs:
  - csharp
  - vb
  name: Version
  nameWithType: ApplicationInformation.Version
  fullName: Neutronium.BuildingBlocks.Application.ViewModels.ApplicationInformation.Version
  type: Property
  source:
    remote:
      path: Neutronium.BuildingBlocks.Application/ViewModels/ApplicationInformation.cs
      branch: master
      repo: https://github.com/NeutroniumCore/Neutronium.BuildingBlocks.git
    id: Version
    path: ../Neutronium.BuildingBlocks.Application/ViewModels/ApplicationInformation.cs
    startLine: 26
  assemblies:
  - Neutronium.BuildingBlocks.Application
  namespace: Neutronium.BuildingBlocks.Application.ViewModels
  summary: "\nApplication version\n"
  example: []
  syntax:
    content: public string Version { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public ReadOnly Property Version As String
  overload: Neutronium.BuildingBlocks.Application.ViewModels.ApplicationInformation.Version*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Neutronium.BuildingBlocks.Application.ViewModels.ApplicationInformation.MadeBy
  commentId: P:Neutronium.BuildingBlocks.Application.ViewModels.ApplicationInformation.MadeBy
  id: MadeBy
  parent: Neutronium.BuildingBlocks.Application.ViewModels.ApplicationInformation
  langs:
  - csharp
  - vb
  name: MadeBy
  nameWithType: ApplicationInformation.MadeBy
  fullName: Neutronium.BuildingBlocks.Application.ViewModels.ApplicationInformation.MadeBy
  type: Property
  source:
    remote:
      path: Neutronium.BuildingBlocks.Application/ViewModels/ApplicationInformation.cs
      branch: master
      repo: https://github.com/NeutroniumCore/Neutronium.BuildingBlocks.git
    id: MadeBy
    path: ../Neutronium.BuildingBlocks.Application/ViewModels/ApplicationInformation.cs
    startLine: 31
  assemblies:
  - Neutronium.BuildingBlocks.Application
  namespace: Neutronium.BuildingBlocks.Application.ViewModels
  summary: "\nApplication author\n"
  example: []
  syntax:
    content: public string MadeBy { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public ReadOnly Property MadeBy As String
  overload: Neutronium.BuildingBlocks.Application.ViewModels.ApplicationInformation.MadeBy*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Neutronium.BuildingBlocks.Application.ViewModels.ApplicationInformation.Year
  commentId: P:Neutronium.BuildingBlocks.Application.ViewModels.ApplicationInformation.Year
  id: Year
  parent: Neutronium.BuildingBlocks.Application.ViewModels.ApplicationInformation
  langs:
  - csharp
  - vb
  name: Year
  nameWithType: ApplicationInformation.Year
  fullName: Neutronium.BuildingBlocks.Application.ViewModels.ApplicationInformation.Year
  type: Property
  source:
    remote:
      path: Neutronium.BuildingBlocks.Application/ViewModels/ApplicationInformation.cs
      branch: master
      repo: https://github.com/NeutroniumCore/Neutronium.BuildingBlocks.git
    id: Year
    path: ../Neutronium.BuildingBlocks.Application/ViewModels/ApplicationInformation.cs
    startLine: 36
  assemblies:
  - Neutronium.BuildingBlocks.Application
  namespace: Neutronium.BuildingBlocks.Application.ViewModels
  summary: "\nCopyright year\n"
  example: []
  syntax:
    content: public int Year { get; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public ReadOnly Property Year As Integer
  overload: Neutronium.BuildingBlocks.Application.ViewModels.ApplicationInformation.Year*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
references:
- uid: Neutronium.BuildingBlocks.Application.ViewModels
  commentId: N:Neutronium.BuildingBlocks.Application.ViewModels
  name: Neutronium.BuildingBlocks.Application.ViewModels
  nameWithType: Neutronium.BuildingBlocks.Application.ViewModels
  fullName: Neutronium.BuildingBlocks.Application.ViewModels
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Neutronium.BuildingBlocks.Application.ViewModels.ApplicationInformation.#ctor*
  commentId: Overload:Neutronium.BuildingBlocks.Application.ViewModels.ApplicationInformation.#ctor
  name: ApplicationInformation
  nameWithType: ApplicationInformation.ApplicationInformation
  fullName: Neutronium.BuildingBlocks.Application.ViewModels.ApplicationInformation.ApplicationInformation
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Neutronium.BuildingBlocks.Application.ViewModels.ApplicationInformation.Name*
  commentId: Overload:Neutronium.BuildingBlocks.Application.ViewModels.ApplicationInformation.Name
  name: Name
  nameWithType: ApplicationInformation.Name
  fullName: Neutronium.BuildingBlocks.Application.ViewModels.ApplicationInformation.Name
- uid: Neutronium.BuildingBlocks.Application.ViewModels.ApplicationInformation.Version*
  commentId: Overload:Neutronium.BuildingBlocks.Application.ViewModels.ApplicationInformation.Version
  name: Version
  nameWithType: ApplicationInformation.Version
  fullName: Neutronium.BuildingBlocks.Application.ViewModels.ApplicationInformation.Version
- uid: Neutronium.BuildingBlocks.Application.ViewModels.ApplicationInformation.MadeBy*
  commentId: Overload:Neutronium.BuildingBlocks.Application.ViewModels.ApplicationInformation.MadeBy
  name: MadeBy
  nameWithType: ApplicationInformation.MadeBy
  fullName: Neutronium.BuildingBlocks.Application.ViewModels.ApplicationInformation.MadeBy
- uid: Neutronium.BuildingBlocks.Application.ViewModels.ApplicationInformation.Year*
  commentId: Overload:Neutronium.BuildingBlocks.Application.ViewModels.ApplicationInformation.Year
  name: Year
  nameWithType: ApplicationInformation.Year
  fullName: Neutronium.BuildingBlocks.Application.ViewModels.ApplicationInformation.Year
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
