### YamlMime:ManagedReference
items:
- uid: Neutronium.BuildingBlocks.Application.Navigation.RoutedEventArgs
  commentId: T:Neutronium.BuildingBlocks.Application.Navigation.RoutedEventArgs
  id: RoutedEventArgs
  parent: Neutronium.BuildingBlocks.Application.Navigation
  children:
  - Neutronium.BuildingBlocks.Application.Navigation.RoutedEventArgs.#ctor(Neutronium.BuildingBlocks.Application.Navigation.RouteInfo)
  - Neutronium.BuildingBlocks.Application.Navigation.RoutedEventArgs.#ctor(System.Object,System.String)
  - Neutronium.BuildingBlocks.Application.Navigation.RoutedEventArgs.NewRoute
  - Neutronium.BuildingBlocks.Application.Navigation.RoutedEventArgs.ToString
  langs:
  - csharp
  - vb
  name: RoutedEventArgs
  nameWithType: RoutedEventArgs
  fullName: Neutronium.BuildingBlocks.Application.Navigation.RoutedEventArgs
  type: Class
  source:
    remote:
      path: Neutronium.BuildingBlocks.Application/Navigation/RoutedEventArgs.cs
      branch: master
      repo: https://github.com/NeutroniumCore/ViewModel.Tools.git
    id: RoutedEventArgs
    path: ../Neutronium.BuildingBlocks.Application/Navigation/RoutedEventArgs.cs
    startLine: 4
  assemblies:
  - Neutronium.BuildingBlocks.Application
  namespace: Neutronium.BuildingBlocks.Application.Navigation
  syntax:
    content: 'public class RoutedEventArgs : EventArgs'
    content.vb: >-
      Public Class RoutedEventArgs
          Inherits EventArgs
  inheritance:
  - System.Object
  - System.EventArgs
  inheritedMembers:
  - System.EventArgs.Empty
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Neutronium.BuildingBlocks.Application.Navigation.RoutedEventArgs.NewRoute
  commentId: P:Neutronium.BuildingBlocks.Application.Navigation.RoutedEventArgs.NewRoute
  id: NewRoute
  parent: Neutronium.BuildingBlocks.Application.Navigation.RoutedEventArgs
  langs:
  - csharp
  - vb
  name: NewRoute
  nameWithType: RoutedEventArgs.NewRoute
  fullName: Neutronium.BuildingBlocks.Application.Navigation.RoutedEventArgs.NewRoute
  type: Property
  source:
    remote:
      path: Neutronium.BuildingBlocks.Application/Navigation/RoutedEventArgs.cs
      branch: master
      repo: https://github.com/NeutroniumCore/ViewModel.Tools.git
    id: NewRoute
    path: ../Neutronium.BuildingBlocks.Application/Navigation/RoutedEventArgs.cs
    startLine: 6
  assemblies:
  - Neutronium.BuildingBlocks.Application
  namespace: Neutronium.BuildingBlocks.Application.Navigation
  syntax:
    content: public RouteInfo NewRoute { get; }
    parameters: []
    return:
      type: Neutronium.BuildingBlocks.Application.Navigation.RouteInfo
    content.vb: Public ReadOnly Property NewRoute As RouteInfo
  overload: Neutronium.BuildingBlocks.Application.Navigation.RoutedEventArgs.NewRoute*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Neutronium.BuildingBlocks.Application.Navigation.RoutedEventArgs.#ctor(System.Object,System.String)
  commentId: M:Neutronium.BuildingBlocks.Application.Navigation.RoutedEventArgs.#ctor(System.Object,System.String)
  id: '#ctor(System.Object,System.String)'
  parent: Neutronium.BuildingBlocks.Application.Navigation.RoutedEventArgs
  langs:
  - csharp
  - vb
  name: RoutedEventArgs(Object, String)
  nameWithType: RoutedEventArgs.RoutedEventArgs(Object, String)
  fullName: Neutronium.BuildingBlocks.Application.Navigation.RoutedEventArgs.RoutedEventArgs(System.Object, System.String)
  type: Constructor
  source:
    remote:
      path: Neutronium.BuildingBlocks.Application/Navigation/RoutedEventArgs.cs
      branch: master
      repo: https://github.com/NeutroniumCore/ViewModel.Tools.git
    id: .ctor
    path: ../Neutronium.BuildingBlocks.Application/Navigation/RoutedEventArgs.cs
    startLine: 12
  assemblies:
  - Neutronium.BuildingBlocks.Application
  namespace: Neutronium.BuildingBlocks.Application.Navigation
  syntax:
    content: public RoutedEventArgs(object viewModel, string routeName)
    parameters:
    - id: viewModel
      type: System.Object
    - id: routeName
      type: System.String
    content.vb: Public Sub New(viewModel As Object, routeName As String)
  overload: Neutronium.BuildingBlocks.Application.Navigation.RoutedEventArgs.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Neutronium.BuildingBlocks.Application.Navigation.RoutedEventArgs.#ctor(Neutronium.BuildingBlocks.Application.Navigation.RouteInfo)
  commentId: M:Neutronium.BuildingBlocks.Application.Navigation.RoutedEventArgs.#ctor(Neutronium.BuildingBlocks.Application.Navigation.RouteInfo)
  id: '#ctor(Neutronium.BuildingBlocks.Application.Navigation.RouteInfo)'
  parent: Neutronium.BuildingBlocks.Application.Navigation.RoutedEventArgs
  langs:
  - csharp
  - vb
  name: RoutedEventArgs(RouteInfo)
  nameWithType: RoutedEventArgs.RoutedEventArgs(RouteInfo)
  fullName: Neutronium.BuildingBlocks.Application.Navigation.RoutedEventArgs.RoutedEventArgs(Neutronium.BuildingBlocks.Application.Navigation.RouteInfo)
  type: Constructor
  source:
    remote:
      path: Neutronium.BuildingBlocks.Application/Navigation/RoutedEventArgs.cs
      branch: master
      repo: https://github.com/NeutroniumCore/ViewModel.Tools.git
    id: .ctor
    path: ../Neutronium.BuildingBlocks.Application/Navigation/RoutedEventArgs.cs
    startLine: 17
  assemblies:
  - Neutronium.BuildingBlocks.Application
  namespace: Neutronium.BuildingBlocks.Application.Navigation
  syntax:
    content: public RoutedEventArgs(RouteInfo route)
    parameters:
    - id: route
      type: Neutronium.BuildingBlocks.Application.Navigation.RouteInfo
    content.vb: Public Sub New(route As RouteInfo)
  overload: Neutronium.BuildingBlocks.Application.Navigation.RoutedEventArgs.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Neutronium.BuildingBlocks.Application.Navigation.RoutedEventArgs.ToString
  commentId: M:Neutronium.BuildingBlocks.Application.Navigation.RoutedEventArgs.ToString
  id: ToString
  parent: Neutronium.BuildingBlocks.Application.Navigation.RoutedEventArgs
  langs:
  - csharp
  - vb
  name: ToString()
  nameWithType: RoutedEventArgs.ToString()
  fullName: Neutronium.BuildingBlocks.Application.Navigation.RoutedEventArgs.ToString()
  type: Method
  source:
    remote:
      path: Neutronium.BuildingBlocks.Application/Navigation/RoutedEventArgs.cs
      branch: master
      repo: https://github.com/NeutroniumCore/ViewModel.Tools.git
    id: ToString
    path: ../Neutronium.BuildingBlocks.Application/Navigation/RoutedEventArgs.cs
    startLine: 22
  assemblies:
  - Neutronium.BuildingBlocks.Application
  namespace: Neutronium.BuildingBlocks.Application.Navigation
  syntax:
    content: public override string ToString()
    return:
      type: System.String
    content.vb: Public Overrides Function ToString As String
  overridden: System.Object.ToString
  overload: Neutronium.BuildingBlocks.Application.Navigation.RoutedEventArgs.ToString*
  modifiers.csharp:
  - public
  - override
  modifiers.vb:
  - Public
  - Overrides
references:
- uid: Neutronium.BuildingBlocks.Application.Navigation
  commentId: N:Neutronium.BuildingBlocks.Application.Navigation
  name: Neutronium.BuildingBlocks.Application.Navigation
  nameWithType: Neutronium.BuildingBlocks.Application.Navigation
  fullName: Neutronium.BuildingBlocks.Application.Navigation
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.EventArgs
  commentId: T:System.EventArgs
  parent: System
  isExternal: true
  name: EventArgs
  nameWithType: EventArgs
  fullName: System.EventArgs
- uid: System.EventArgs.Empty
  commentId: F:System.EventArgs.Empty
  parent: System.EventArgs
  isExternal: true
  name: Empty
  nameWithType: EventArgs.Empty
  fullName: System.EventArgs.Empty
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Neutronium.BuildingBlocks.Application.Navigation.RoutedEventArgs.NewRoute*
  commentId: Overload:Neutronium.BuildingBlocks.Application.Navigation.RoutedEventArgs.NewRoute
  name: NewRoute
  nameWithType: RoutedEventArgs.NewRoute
  fullName: Neutronium.BuildingBlocks.Application.Navigation.RoutedEventArgs.NewRoute
- uid: Neutronium.BuildingBlocks.Application.Navigation.RouteInfo
  commentId: T:Neutronium.BuildingBlocks.Application.Navigation.RouteInfo
  parent: Neutronium.BuildingBlocks.Application.Navigation
  name: RouteInfo
  nameWithType: RouteInfo
  fullName: Neutronium.BuildingBlocks.Application.Navigation.RouteInfo
- uid: Neutronium.BuildingBlocks.Application.Navigation.RoutedEventArgs.#ctor*
  commentId: Overload:Neutronium.BuildingBlocks.Application.Navigation.RoutedEventArgs.#ctor
  name: RoutedEventArgs
  nameWithType: RoutedEventArgs.RoutedEventArgs
  fullName: Neutronium.BuildingBlocks.Application.Navigation.RoutedEventArgs.RoutedEventArgs
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: Neutronium.BuildingBlocks.Application.Navigation.RoutedEventArgs.ToString*
  commentId: Overload:Neutronium.BuildingBlocks.Application.Navigation.RoutedEventArgs.ToString
  name: ToString
  nameWithType: RoutedEventArgs.ToString
  fullName: Neutronium.BuildingBlocks.Application.Navigation.RoutedEventArgs.ToString
