### YamlMime:ManagedReference
items:
- uid: Neutronium.BuildingBlocks.Application.Navigation.RouteDestination
  commentId: T:Neutronium.BuildingBlocks.Application.Navigation.RouteDestination
  id: RouteDestination
  parent: Neutronium.BuildingBlocks.Application.Navigation
  children:
  - Neutronium.BuildingBlocks.Application.Navigation.RouteDestination.#ctor(System.Type,System.String,System.String)
  - Neutronium.BuildingBlocks.Application.Navigation.RouteDestination.Context
  - Neutronium.BuildingBlocks.Application.Navigation.RouteDestination.ResolutionKey
  - Neutronium.BuildingBlocks.Application.Navigation.RouteDestination.Type
  langs:
  - csharp
  - vb
  name: RouteDestination
  nameWithType: RouteDestination
  fullName: Neutronium.BuildingBlocks.Application.Navigation.RouteDestination
  type: Class
  source:
    remote:
      path: Neutronium.BuildingBlocks.Application/Navigation/RouteDestination.cs
      branch: master
      repo: https://github.com/NeutroniumCore/ViewModel.Tools.git
    id: RouteDestination
    path: ../Neutronium.BuildingBlocks.Application/Navigation/RouteDestination.cs
    startLine: 7
  assemblies:
  - Neutronium.BuildingBlocks.Application
  namespace: Neutronium.BuildingBlocks.Application.Navigation
  summary: "\nRoute destination\n"
  example: []
  syntax:
    content: public class RouteDestination
    content.vb: Public Class RouteDestination
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Neutronium.BuildingBlocks.Application.Navigation.RouteDestination.Type
  commentId: P:Neutronium.BuildingBlocks.Application.Navigation.RouteDestination.Type
  id: Type
  parent: Neutronium.BuildingBlocks.Application.Navigation.RouteDestination
  langs:
  - csharp
  - vb
  name: Type
  nameWithType: RouteDestination.Type
  fullName: Neutronium.BuildingBlocks.Application.Navigation.RouteDestination.Type
  type: Property
  source:
    remote:
      path: Neutronium.BuildingBlocks.Application/Navigation/RouteDestination.cs
      branch: master
      repo: https://github.com/NeutroniumCore/ViewModel.Tools.git
    id: Type
    path: ../Neutronium.BuildingBlocks.Application/Navigation/RouteDestination.cs
    startLine: 12
  assemblies:
  - Neutronium.BuildingBlocks.Application
  namespace: Neutronium.BuildingBlocks.Application.Navigation
  summary: "\nDestination type\n"
  example: []
  syntax:
    content: public Type Type { get; }
    parameters: []
    return:
      type: System.Type
    content.vb: Public ReadOnly Property Type As Type
  overload: Neutronium.BuildingBlocks.Application.Navigation.RouteDestination.Type*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Neutronium.BuildingBlocks.Application.Navigation.RouteDestination.ResolutionKey
  commentId: P:Neutronium.BuildingBlocks.Application.Navigation.RouteDestination.ResolutionKey
  id: ResolutionKey
  parent: Neutronium.BuildingBlocks.Application.Navigation.RouteDestination
  langs:
  - csharp
  - vb
  name: ResolutionKey
  nameWithType: RouteDestination.ResolutionKey
  fullName: Neutronium.BuildingBlocks.Application.Navigation.RouteDestination.ResolutionKey
  type: Property
  source:
    remote:
      path: Neutronium.BuildingBlocks.Application/Navigation/RouteDestination.cs
      branch: master
      repo: https://github.com/NeutroniumCore/ViewModel.Tools.git
    id: ResolutionKey
    path: ../Neutronium.BuildingBlocks.Application/Navigation/RouteDestination.cs
    startLine: 17
  assemblies:
  - Neutronium.BuildingBlocks.Application
  namespace: Neutronium.BuildingBlocks.Application.Navigation
  summary: "\nResolution key to be used in common service locator\n"
  example: []
  syntax:
    content: public string ResolutionKey { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public ReadOnly Property ResolutionKey As String
  overload: Neutronium.BuildingBlocks.Application.Navigation.RouteDestination.ResolutionKey*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Neutronium.BuildingBlocks.Application.Navigation.RouteDestination.Context
  commentId: P:Neutronium.BuildingBlocks.Application.Navigation.RouteDestination.Context
  id: Context
  parent: Neutronium.BuildingBlocks.Application.Navigation.RouteDestination
  langs:
  - csharp
  - vb
  name: Context
  nameWithType: RouteDestination.Context
  fullName: Neutronium.BuildingBlocks.Application.Navigation.RouteDestination.Context
  type: Property
  source:
    remote:
      path: Neutronium.BuildingBlocks.Application/Navigation/RouteDestination.cs
      branch: master
      repo: https://github.com/NeutroniumCore/ViewModel.Tools.git
    id: Context
    path: ../Neutronium.BuildingBlocks.Application/Navigation/RouteDestination.cs
    startLine: 23
  assemblies:
  - Neutronium.BuildingBlocks.Application
  namespace: Neutronium.BuildingBlocks.Application.Navigation
  summary: "\nResolution context as a path.\nNull for route context\n"
  example: []
  syntax:
    content: public string Context { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public ReadOnly Property Context As String
  overload: Neutronium.BuildingBlocks.Application.Navigation.RouteDestination.Context*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Neutronium.BuildingBlocks.Application.Navigation.RouteDestination.#ctor(System.Type,System.String,System.String)
  commentId: M:Neutronium.BuildingBlocks.Application.Navigation.RouteDestination.#ctor(System.Type,System.String,System.String)
  id: '#ctor(System.Type,System.String,System.String)'
  parent: Neutronium.BuildingBlocks.Application.Navigation.RouteDestination
  langs:
  - csharp
  - vb
  name: RouteDestination(Type, String, String)
  nameWithType: RouteDestination.RouteDestination(Type, String, String)
  fullName: Neutronium.BuildingBlocks.Application.Navigation.RouteDestination.RouteDestination(System.Type, System.String, System.String)
  type: Constructor
  source:
    remote:
      path: Neutronium.BuildingBlocks.Application/Navigation/RouteDestination.cs
      branch: master
      repo: https://github.com/NeutroniumCore/ViewModel.Tools.git
    id: .ctor
    path: ../Neutronium.BuildingBlocks.Application/Navigation/RouteDestination.cs
    startLine: 25
  assemblies:
  - Neutronium.BuildingBlocks.Application
  namespace: Neutronium.BuildingBlocks.Application.Navigation
  syntax:
    content: public RouteDestination(Type type, string context = null, string resolutionKey = null)
    parameters:
    - id: type
      type: System.Type
    - id: context
      type: System.String
    - id: resolutionKey
      type: System.String
    content.vb: Public Sub New(type As Type, context As String = Nothing, resolutionKey As String = Nothing)
  overload: Neutronium.BuildingBlocks.Application.Navigation.RouteDestination.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Neutronium.BuildingBlocks.Application.Navigation
  commentId: N:Neutronium.BuildingBlocks.Application.Navigation
  name: Neutronium.BuildingBlocks.Application.Navigation
  nameWithType: Neutronium.BuildingBlocks.Application.Navigation
  fullName: Neutronium.BuildingBlocks.Application.Navigation
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Neutronium.BuildingBlocks.Application.Navigation.RouteDestination.Type*
  commentId: Overload:Neutronium.BuildingBlocks.Application.Navigation.RouteDestination.Type
  name: Type
  nameWithType: RouteDestination.Type
  fullName: Neutronium.BuildingBlocks.Application.Navigation.RouteDestination.Type
- uid: System.Type
  commentId: T:System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: Neutronium.BuildingBlocks.Application.Navigation.RouteDestination.ResolutionKey*
  commentId: Overload:Neutronium.BuildingBlocks.Application.Navigation.RouteDestination.ResolutionKey
  name: ResolutionKey
  nameWithType: RouteDestination.ResolutionKey
  fullName: Neutronium.BuildingBlocks.Application.Navigation.RouteDestination.ResolutionKey
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Neutronium.BuildingBlocks.Application.Navigation.RouteDestination.Context*
  commentId: Overload:Neutronium.BuildingBlocks.Application.Navigation.RouteDestination.Context
  name: Context
  nameWithType: RouteDestination.Context
  fullName: Neutronium.BuildingBlocks.Application.Navigation.RouteDestination.Context
- uid: Neutronium.BuildingBlocks.Application.Navigation.RouteDestination.#ctor*
  commentId: Overload:Neutronium.BuildingBlocks.Application.Navigation.RouteDestination.#ctor
  name: RouteDestination
  nameWithType: RouteDestination.RouteDestination
  fullName: Neutronium.BuildingBlocks.Application.Navigation.RouteDestination.RouteDestination
