### YamlMime:ManagedReference
items:
- uid: Neutronium.BuildingBlocks.Application.Navigation.RoutingEventArgs
  commentId: T:Neutronium.BuildingBlocks.Application.Navigation.RoutingEventArgs
  id: RoutingEventArgs
  parent: Neutronium.BuildingBlocks.Application.Navigation
  children:
  - Neutronium.BuildingBlocks.Application.Navigation.RoutingEventArgs.From
  - Neutronium.BuildingBlocks.Application.Navigation.RoutingEventArgs.RedirectedTo
  - Neutronium.BuildingBlocks.Application.Navigation.RoutingEventArgs.RedirectToRoute(System.String)
  - Neutronium.BuildingBlocks.Application.Navigation.RoutingEventArgs.To
  - Neutronium.BuildingBlocks.Application.Navigation.RoutingEventArgs.ToString
  langs:
  - csharp
  - vb
  name: RoutingEventArgs
  nameWithType: RoutingEventArgs
  fullName: Neutronium.BuildingBlocks.Application.Navigation.RoutingEventArgs
  type: Class
  source:
    remote:
      path: Neutronium.BuildingBlocks.Application/Navigation/RoutingEventArgs.cs
      branch: master
      repo: https://github.com/NeutroniumCore/ViewModel.Tools.git
    id: RoutingEventArgs
    path: ../Neutronium.BuildingBlocks.Application/Navigation/RoutingEventArgs.cs
    startLine: 8
  assemblies:
  - Neutronium.BuildingBlocks.Application
  namespace: Neutronium.BuildingBlocks.Application.Navigation
  summary: "\nRouting event\n"
  example: []
  syntax:
    content: 'public class RoutingEventArgs : CancelEventArgs'
    content.vb: >-
      Public Class RoutingEventArgs
          Inherits CancelEventArgs
  inheritance:
  - System.Object
  - System.EventArgs
  - System.ComponentModel.CancelEventArgs
  inheritedMembers:
  - System.ComponentModel.CancelEventArgs.Cancel
  - System.EventArgs.Empty
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Neutronium.BuildingBlocks.Application.Navigation.RoutingEventArgs.To
  commentId: P:Neutronium.BuildingBlocks.Application.Navigation.RoutingEventArgs.To
  id: To
  parent: Neutronium.BuildingBlocks.Application.Navigation.RoutingEventArgs
  langs:
  - csharp
  - vb
  name: To
  nameWithType: RoutingEventArgs.To
  fullName: Neutronium.BuildingBlocks.Application.Navigation.RoutingEventArgs.To
  type: Property
  source:
    remote:
      path: Neutronium.BuildingBlocks.Application/Navigation/RoutingEventArgs.cs
      branch: master
      repo: https://github.com/NeutroniumCore/ViewModel.Tools.git
    id: To
    path: ../Neutronium.BuildingBlocks.Application/Navigation/RoutingEventArgs.cs
    startLine: 19
  assemblies:
  - Neutronium.BuildingBlocks.Application
  namespace: Neutronium.BuildingBlocks.Application.Navigation
  summary: "\nDestination route\n"
  example: []
  syntax:
    content: public RouteInfo To { get; }
    parameters: []
    return:
      type: Neutronium.BuildingBlocks.Application.Navigation.RouteInfo
    content.vb: Public ReadOnly Property To As RouteInfo
  overload: Neutronium.BuildingBlocks.Application.Navigation.RoutingEventArgs.To*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Neutronium.BuildingBlocks.Application.Navigation.RoutingEventArgs.From
  commentId: P:Neutronium.BuildingBlocks.Application.Navigation.RoutingEventArgs.From
  id: From
  parent: Neutronium.BuildingBlocks.Application.Navigation.RoutingEventArgs
  langs:
  - csharp
  - vb
  name: From
  nameWithType: RoutingEventArgs.From
  fullName: Neutronium.BuildingBlocks.Application.Navigation.RoutingEventArgs.From
  type: Property
  source:
    remote:
      path: Neutronium.BuildingBlocks.Application/Navigation/RoutingEventArgs.cs
      branch: master
      repo: https://github.com/NeutroniumCore/ViewModel.Tools.git
    id: From
    path: ../Neutronium.BuildingBlocks.Application/Navigation/RoutingEventArgs.cs
    startLine: 24
  assemblies:
  - Neutronium.BuildingBlocks.Application
  namespace: Neutronium.BuildingBlocks.Application.Navigation
  summary: "\nCurrent route\n"
  example: []
  syntax:
    content: public RouteInfo From { get; }
    parameters: []
    return:
      type: Neutronium.BuildingBlocks.Application.Navigation.RouteInfo
    content.vb: Public ReadOnly Property From As RouteInfo
  overload: Neutronium.BuildingBlocks.Application.Navigation.RoutingEventArgs.From*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Neutronium.BuildingBlocks.Application.Navigation.RoutingEventArgs.RedirectedTo
  commentId: P:Neutronium.BuildingBlocks.Application.Navigation.RoutingEventArgs.RedirectedTo
  id: RedirectedTo
  parent: Neutronium.BuildingBlocks.Application.Navigation.RoutingEventArgs
  langs:
  - csharp
  - vb
  name: RedirectedTo
  nameWithType: RoutingEventArgs.RedirectedTo
  fullName: Neutronium.BuildingBlocks.Application.Navigation.RoutingEventArgs.RedirectedTo
  type: Property
  source:
    remote:
      path: Neutronium.BuildingBlocks.Application/Navigation/RoutingEventArgs.cs
      branch: master
      repo: https://github.com/NeutroniumCore/ViewModel.Tools.git
    id: RedirectedTo
    path: ../Neutronium.BuildingBlocks.Application/Navigation/RoutingEventArgs.cs
    startLine: 29
  assemblies:
  - Neutronium.BuildingBlocks.Application
  namespace: Neutronium.BuildingBlocks.Application.Navigation
  summary: "\nRedirected route\n"
  example: []
  syntax:
    content: public string RedirectedTo { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public ReadOnly Property RedirectedTo As String
  overload: Neutronium.BuildingBlocks.Application.Navigation.RoutingEventArgs.RedirectedTo*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Neutronium.BuildingBlocks.Application.Navigation.RoutingEventArgs.RedirectToRoute(System.String)
  commentId: M:Neutronium.BuildingBlocks.Application.Navigation.RoutingEventArgs.RedirectToRoute(System.String)
  id: RedirectToRoute(System.String)
  parent: Neutronium.BuildingBlocks.Application.Navigation.RoutingEventArgs
  langs:
  - csharp
  - vb
  name: RedirectToRoute(String)
  nameWithType: RoutingEventArgs.RedirectToRoute(String)
  fullName: Neutronium.BuildingBlocks.Application.Navigation.RoutingEventArgs.RedirectToRoute(System.String)
  type: Method
  source:
    remote:
      path: Neutronium.BuildingBlocks.Application/Navigation/RoutingEventArgs.cs
      branch: master
      repo: https://github.com/NeutroniumCore/ViewModel.Tools.git
    id: RedirectToRoute
    path: ../Neutronium.BuildingBlocks.Application/Navigation/RoutingEventArgs.cs
    startLine: 35
  assemblies:
  - Neutronium.BuildingBlocks.Application
  namespace: Neutronium.BuildingBlocks.Application.Navigation
  summary: "\nRedirect to the given route\n"
  example: []
  syntax:
    content: public void RedirectToRoute(string newRouteName)
    parameters:
    - id: newRouteName
      type: System.String
      description: ''
    content.vb: Public Sub RedirectToRoute(newRouteName As String)
  overload: Neutronium.BuildingBlocks.Application.Navigation.RoutingEventArgs.RedirectToRoute*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Neutronium.BuildingBlocks.Application.Navigation.RoutingEventArgs.ToString
  commentId: M:Neutronium.BuildingBlocks.Application.Navigation.RoutingEventArgs.ToString
  id: ToString
  parent: Neutronium.BuildingBlocks.Application.Navigation.RoutingEventArgs
  langs:
  - csharp
  - vb
  name: ToString()
  nameWithType: RoutingEventArgs.ToString()
  fullName: Neutronium.BuildingBlocks.Application.Navigation.RoutingEventArgs.ToString()
  type: Method
  source:
    remote:
      path: Neutronium.BuildingBlocks.Application/Navigation/RoutingEventArgs.cs
      branch: master
      repo: https://github.com/NeutroniumCore/ViewModel.Tools.git
    id: ToString
    path: ../Neutronium.BuildingBlocks.Application/Navigation/RoutingEventArgs.cs
    startLine: 43
  assemblies:
  - Neutronium.BuildingBlocks.Application
  namespace: Neutronium.BuildingBlocks.Application.Navigation
  syntax:
    content: public override string ToString()
    return:
      type: System.String
    content.vb: Public Overrides Function ToString As String
  overridden: System.Object.ToString
  overload: Neutronium.BuildingBlocks.Application.Navigation.RoutingEventArgs.ToString*
  modifiers.csharp:
  - public
  - override
  modifiers.vb:
  - Public
  - Overrides
references:
- uid: Neutronium.BuildingBlocks.Application.Navigation
  commentId: N:Neutronium.BuildingBlocks.Application.Navigation
  name: Neutronium.BuildingBlocks.Application.Navigation
  nameWithType: Neutronium.BuildingBlocks.Application.Navigation
  fullName: Neutronium.BuildingBlocks.Application.Navigation
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.EventArgs
  commentId: T:System.EventArgs
  parent: System
  isExternal: true
  name: EventArgs
  nameWithType: EventArgs
  fullName: System.EventArgs
- uid: System.ComponentModel.CancelEventArgs
  commentId: T:System.ComponentModel.CancelEventArgs
  parent: System.ComponentModel
  isExternal: true
  name: CancelEventArgs
  nameWithType: CancelEventArgs
  fullName: System.ComponentModel.CancelEventArgs
- uid: System.ComponentModel.CancelEventArgs.Cancel
  commentId: P:System.ComponentModel.CancelEventArgs.Cancel
  parent: System.ComponentModel.CancelEventArgs
  isExternal: true
  name: Cancel
  nameWithType: CancelEventArgs.Cancel
  fullName: System.ComponentModel.CancelEventArgs.Cancel
- uid: System.EventArgs.Empty
  commentId: F:System.EventArgs.Empty
  parent: System.EventArgs
  isExternal: true
  name: Empty
  nameWithType: EventArgs.Empty
  fullName: System.EventArgs.Empty
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: System.ComponentModel
  commentId: N:System.ComponentModel
  isExternal: true
  name: System.ComponentModel
  nameWithType: System.ComponentModel
  fullName: System.ComponentModel
- uid: Neutronium.BuildingBlocks.Application.Navigation.RoutingEventArgs.To*
  commentId: Overload:Neutronium.BuildingBlocks.Application.Navigation.RoutingEventArgs.To
  name: To
  nameWithType: RoutingEventArgs.To
  fullName: Neutronium.BuildingBlocks.Application.Navigation.RoutingEventArgs.To
- uid: Neutronium.BuildingBlocks.Application.Navigation.RouteInfo
  commentId: T:Neutronium.BuildingBlocks.Application.Navigation.RouteInfo
  parent: Neutronium.BuildingBlocks.Application.Navigation
  name: RouteInfo
  nameWithType: RouteInfo
  fullName: Neutronium.BuildingBlocks.Application.Navigation.RouteInfo
- uid: Neutronium.BuildingBlocks.Application.Navigation.RoutingEventArgs.From*
  commentId: Overload:Neutronium.BuildingBlocks.Application.Navigation.RoutingEventArgs.From
  name: From
  nameWithType: RoutingEventArgs.From
  fullName: Neutronium.BuildingBlocks.Application.Navigation.RoutingEventArgs.From
- uid: Neutronium.BuildingBlocks.Application.Navigation.RoutingEventArgs.RedirectedTo*
  commentId: Overload:Neutronium.BuildingBlocks.Application.Navigation.RoutingEventArgs.RedirectedTo
  name: RedirectedTo
  nameWithType: RoutingEventArgs.RedirectedTo
  fullName: Neutronium.BuildingBlocks.Application.Navigation.RoutingEventArgs.RedirectedTo
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Neutronium.BuildingBlocks.Application.Navigation.RoutingEventArgs.RedirectToRoute*
  commentId: Overload:Neutronium.BuildingBlocks.Application.Navigation.RoutingEventArgs.RedirectToRoute
  name: RedirectToRoute
  nameWithType: RoutingEventArgs.RedirectToRoute
  fullName: Neutronium.BuildingBlocks.Application.Navigation.RoutingEventArgs.RedirectToRoute
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: Neutronium.BuildingBlocks.Application.Navigation.RoutingEventArgs.ToString*
  commentId: Overload:Neutronium.BuildingBlocks.Application.Navigation.RoutingEventArgs.ToString
  name: ToString
  nameWithType: RoutingEventArgs.ToString
  fullName: Neutronium.BuildingBlocks.Application.Navigation.RoutingEventArgs.ToString
