### YamlMime:ManagedReference
items:
- uid: Neutronium.BuildingBlocks.ApplicationTools.IChooserCommand`1
  commentId: T:Neutronium.BuildingBlocks.ApplicationTools.IChooserCommand`1
  id: IChooserCommand`1
  parent: Neutronium.BuildingBlocks.ApplicationTools
  children:
  - Neutronium.BuildingBlocks.ApplicationTools.IChooserCommand`1.CanBeExecuted
  - Neutronium.BuildingBlocks.ApplicationTools.IChooserCommand`1.Choose
  - Neutronium.BuildingBlocks.ApplicationTools.IChooserCommand`1.Picker
  - Neutronium.BuildingBlocks.ApplicationTools.IChooserCommand`1.Results
  langs:
  - csharp
  - vb
  name: IChooserCommand<T>
  nameWithType: IChooserCommand<T>
  fullName: Neutronium.BuildingBlocks.ApplicationTools.IChooserCommand<T>
  type: Interface
  source:
    remote:
      path: Neutronium.BuildingBlocks.ApplicationTools/IChooserCommand.cs
      branch: master
      repo: https://github.com/NeutroniumCore/Neutronium.BuildingBlocks.git
    id: IChooserCommand
    path: ../Neutronium.BuildingBlocks.ApplicationTools/IChooserCommand.cs
    startLine: 9
  assemblies:
  - Neutronium.BuildingBlocks.ApplicationTools
  namespace: Neutronium.BuildingBlocks.ApplicationTools
  summary: "\nHelper to create a command from <xref href=\"Neutronium.BuildingBlocks.ApplicationTools.IFilePicker\" data-throw-if-not-resolved=\"false\"></xref> or <xref href=\"Neutronium.BuildingBlocks.ApplicationTools.IFolderPicker\" data-throw-if-not-resolved=\"false\"></xref>\n"
  example: []
  syntax:
    content: >-
      public interface IChooserCommand<out T>
          where T : IIODialog
    typeParameters:
    - id: T
      description: ''
    content.vb: Public Interface IChooserCommand(Of Out T As IIODialog)
  nameWithType.vb: IChooserCommand(Of T)
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
  fullName.vb: Neutronium.BuildingBlocks.ApplicationTools.IChooserCommand(Of T)
  name.vb: IChooserCommand(Of T)
- uid: Neutronium.BuildingBlocks.ApplicationTools.IChooserCommand`1.CanBeExecuted
  commentId: P:Neutronium.BuildingBlocks.ApplicationTools.IChooserCommand`1.CanBeExecuted
  id: CanBeExecuted
  parent: Neutronium.BuildingBlocks.ApplicationTools.IChooserCommand`1
  langs:
  - csharp
  - vb
  name: CanBeExecuted
  nameWithType: IChooserCommand<T>.CanBeExecuted
  fullName: Neutronium.BuildingBlocks.ApplicationTools.IChooserCommand<T>.CanBeExecuted
  type: Property
  source:
    remote:
      path: Neutronium.BuildingBlocks.ApplicationTools/IChooserCommand.cs
      branch: master
      repo: https://github.com/NeutroniumCore/Neutronium.BuildingBlocks.git
    id: CanBeExecuted
    path: ../Neutronium.BuildingBlocks.ApplicationTools/IChooserCommand.cs
    startLine: 14
  assemblies:
  - Neutronium.BuildingBlocks.ApplicationTools
  namespace: Neutronium.BuildingBlocks.ApplicationTools
  summary: "\nCanBeExecuted\n"
  example: []
  syntax:
    content: bool CanBeExecuted { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Property CanBeExecuted As Boolean
  overload: Neutronium.BuildingBlocks.ApplicationTools.IChooserCommand`1.CanBeExecuted*
  nameWithType.vb: IChooserCommand(Of T).CanBeExecuted
  modifiers.csharp:
  - get
  - set
  fullName.vb: Neutronium.BuildingBlocks.ApplicationTools.IChooserCommand(Of T).CanBeExecuted
- uid: Neutronium.BuildingBlocks.ApplicationTools.IChooserCommand`1.Picker
  commentId: P:Neutronium.BuildingBlocks.ApplicationTools.IChooserCommand`1.Picker
  id: Picker
  parent: Neutronium.BuildingBlocks.ApplicationTools.IChooserCommand`1
  langs:
  - csharp
  - vb
  name: Picker
  nameWithType: IChooserCommand<T>.Picker
  fullName: Neutronium.BuildingBlocks.ApplicationTools.IChooserCommand<T>.Picker
  type: Property
  source:
    remote:
      path: Neutronium.BuildingBlocks.ApplicationTools/IChooserCommand.cs
      branch: master
      repo: https://github.com/NeutroniumCore/Neutronium.BuildingBlocks.git
    id: Picker
    path: ../Neutronium.BuildingBlocks.ApplicationTools/IChooserCommand.cs
    startLine: 19
  assemblies:
  - Neutronium.BuildingBlocks.ApplicationTools
  namespace: Neutronium.BuildingBlocks.ApplicationTools
  summary: "\nFile or Folder picker instance\n"
  example: []
  syntax:
    content: T Picker { get; }
    parameters: []
    return:
      type: '{T}'
    content.vb: ReadOnly Property Picker As T
  overload: Neutronium.BuildingBlocks.ApplicationTools.IChooserCommand`1.Picker*
  nameWithType.vb: IChooserCommand(Of T).Picker
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
  fullName.vb: Neutronium.BuildingBlocks.ApplicationTools.IChooserCommand(Of T).Picker
- uid: Neutronium.BuildingBlocks.ApplicationTools.IChooserCommand`1.Results
  commentId: P:Neutronium.BuildingBlocks.ApplicationTools.IChooserCommand`1.Results
  id: Results
  parent: Neutronium.BuildingBlocks.ApplicationTools.IChooserCommand`1
  langs:
  - csharp
  - vb
  name: Results
  nameWithType: IChooserCommand<T>.Results
  fullName: Neutronium.BuildingBlocks.ApplicationTools.IChooserCommand<T>.Results
  type: Property
  source:
    remote:
      path: Neutronium.BuildingBlocks.ApplicationTools/IChooserCommand.cs
      branch: master
      repo: https://github.com/NeutroniumCore/Neutronium.BuildingBlocks.git
    id: Results
    path: ../Neutronium.BuildingBlocks.ApplicationTools/IChooserCommand.cs
    startLine: 24
  assemblies:
  - Neutronium.BuildingBlocks.ApplicationTools
  namespace: Neutronium.BuildingBlocks.ApplicationTools
  summary: "\nResults as observable\n"
  example: []
  syntax:
    content: IObservable<string> Results { get; }
    parameters: []
    return:
      type: System.IObservable{System.String}
    content.vb: ReadOnly Property Results As IObservable(Of String)
  overload: Neutronium.BuildingBlocks.ApplicationTools.IChooserCommand`1.Results*
  nameWithType.vb: IChooserCommand(Of T).Results
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
  fullName.vb: Neutronium.BuildingBlocks.ApplicationTools.IChooserCommand(Of T).Results
- uid: Neutronium.BuildingBlocks.ApplicationTools.IChooserCommand`1.Choose
  commentId: P:Neutronium.BuildingBlocks.ApplicationTools.IChooserCommand`1.Choose
  id: Choose
  parent: Neutronium.BuildingBlocks.ApplicationTools.IChooserCommand`1
  langs:
  - csharp
  - vb
  name: Choose
  nameWithType: IChooserCommand<T>.Choose
  fullName: Neutronium.BuildingBlocks.ApplicationTools.IChooserCommand<T>.Choose
  type: Property
  source:
    remote:
      path: Neutronium.BuildingBlocks.ApplicationTools/IChooserCommand.cs
      branch: master
      repo: https://github.com/NeutroniumCore/Neutronium.BuildingBlocks.git
    id: Choose
    path: ../Neutronium.BuildingBlocks.ApplicationTools/IChooserCommand.cs
    startLine: 29
  assemblies:
  - Neutronium.BuildingBlocks.ApplicationTools
  namespace: Neutronium.BuildingBlocks.ApplicationTools
  summary: "\nPicker exposed as command.\n"
  example: []
  syntax:
    content: ICommandWithoutParameter Choose { get; }
    parameters: []
    return:
      type: Neutronium.MVVMComponents.ICommandWithoutParameter
    content.vb: ReadOnly Property Choose As ICommandWithoutParameter
  overload: Neutronium.BuildingBlocks.ApplicationTools.IChooserCommand`1.Choose*
  nameWithType.vb: IChooserCommand(Of T).Choose
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
  fullName.vb: Neutronium.BuildingBlocks.ApplicationTools.IChooserCommand(Of T).Choose
references:
- uid: Neutronium.BuildingBlocks.ApplicationTools.IFilePicker
  commentId: T:Neutronium.BuildingBlocks.ApplicationTools.IFilePicker
  name: IFilePicker
  nameWithType: IFilePicker
  fullName: Neutronium.BuildingBlocks.ApplicationTools.IFilePicker
- uid: Neutronium.BuildingBlocks.ApplicationTools.IFolderPicker
  commentId: T:Neutronium.BuildingBlocks.ApplicationTools.IFolderPicker
  name: IFolderPicker
  nameWithType: IFolderPicker
  fullName: Neutronium.BuildingBlocks.ApplicationTools.IFolderPicker
- uid: Neutronium.BuildingBlocks.ApplicationTools
  commentId: N:Neutronium.BuildingBlocks.ApplicationTools
  name: Neutronium.BuildingBlocks.ApplicationTools
  nameWithType: Neutronium.BuildingBlocks.ApplicationTools
  fullName: Neutronium.BuildingBlocks.ApplicationTools
- uid: Neutronium.BuildingBlocks.ApplicationTools.IChooserCommand`1.CanBeExecuted*
  commentId: Overload:Neutronium.BuildingBlocks.ApplicationTools.IChooserCommand`1.CanBeExecuted
  name: CanBeExecuted
  nameWithType: IChooserCommand<T>.CanBeExecuted
  fullName: Neutronium.BuildingBlocks.ApplicationTools.IChooserCommand<T>.CanBeExecuted
  nameWithType.vb: IChooserCommand(Of T).CanBeExecuted
  fullName.vb: Neutronium.BuildingBlocks.ApplicationTools.IChooserCommand(Of T).CanBeExecuted
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Neutronium.BuildingBlocks.ApplicationTools.IChooserCommand`1.Picker*
  commentId: Overload:Neutronium.BuildingBlocks.ApplicationTools.IChooserCommand`1.Picker
  name: Picker
  nameWithType: IChooserCommand<T>.Picker
  fullName: Neutronium.BuildingBlocks.ApplicationTools.IChooserCommand<T>.Picker
  nameWithType.vb: IChooserCommand(Of T).Picker
  fullName.vb: Neutronium.BuildingBlocks.ApplicationTools.IChooserCommand(Of T).Picker
- uid: '{T}'
  commentId: '!:T'
  definition: T
  name: T
  nameWithType: T
  fullName: T
- uid: T
  name: T
  nameWithType: T
  fullName: T
- uid: Neutronium.BuildingBlocks.ApplicationTools.IChooserCommand`1.Results*
  commentId: Overload:Neutronium.BuildingBlocks.ApplicationTools.IChooserCommand`1.Results
  name: Results
  nameWithType: IChooserCommand<T>.Results
  fullName: Neutronium.BuildingBlocks.ApplicationTools.IChooserCommand<T>.Results
  nameWithType.vb: IChooserCommand(Of T).Results
  fullName.vb: Neutronium.BuildingBlocks.ApplicationTools.IChooserCommand(Of T).Results
- uid: System.IObservable{System.String}
  commentId: T:System.IObservable{System.String}
  parent: System
  definition: System.IObservable`1
  name: IObservable<String>
  nameWithType: IObservable<String>
  fullName: System.IObservable<System.String>
  nameWithType.vb: IObservable(Of String)
  fullName.vb: System.IObservable(Of System.String)
  name.vb: IObservable(Of String)
  spec.csharp:
  - uid: System.IObservable`1
    name: IObservable
    nameWithType: IObservable
    fullName: System.IObservable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.IObservable`1
    name: IObservable
    nameWithType: IObservable
    fullName: System.IObservable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.IObservable`1
  commentId: T:System.IObservable`1
  isExternal: true
  name: IObservable<T>
  nameWithType: IObservable<T>
  fullName: System.IObservable<T>
  nameWithType.vb: IObservable(Of T)
  fullName.vb: System.IObservable(Of T)
  name.vb: IObservable(Of T)
  spec.csharp:
  - uid: System.IObservable`1
    name: IObservable
    nameWithType: IObservable
    fullName: System.IObservable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.IObservable`1
    name: IObservable
    nameWithType: IObservable
    fullName: System.IObservable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: Neutronium.BuildingBlocks.ApplicationTools.IChooserCommand`1.Choose*
  commentId: Overload:Neutronium.BuildingBlocks.ApplicationTools.IChooserCommand`1.Choose
  name: Choose
  nameWithType: IChooserCommand<T>.Choose
  fullName: Neutronium.BuildingBlocks.ApplicationTools.IChooserCommand<T>.Choose
  nameWithType.vb: IChooserCommand(Of T).Choose
  fullName.vb: Neutronium.BuildingBlocks.ApplicationTools.IChooserCommand(Of T).Choose
- uid: Neutronium.MVVMComponents.ICommandWithoutParameter
  commentId: T:Neutronium.MVVMComponents.ICommandWithoutParameter
  parent: Neutronium.MVVMComponents
  isExternal: true
  name: ICommandWithoutParameter
  nameWithType: ICommandWithoutParameter
  fullName: Neutronium.MVVMComponents.ICommandWithoutParameter
- uid: Neutronium.MVVMComponents
  commentId: N:Neutronium.MVVMComponents
  isExternal: true
  name: Neutronium.MVVMComponents
  nameWithType: Neutronium.MVVMComponents
  fullName: Neutronium.MVVMComponents
