### YamlMime:ManagedReference
items:
- uid: Neutronium.BuildingBlocks.ApplicationTools.ITaskCancellableCommand`1
  commentId: T:Neutronium.BuildingBlocks.ApplicationTools.ITaskCancellableCommand`1
  id: ITaskCancellableCommand`1
  parent: Neutronium.BuildingBlocks.ApplicationTools
  children:
  - Neutronium.BuildingBlocks.ApplicationTools.ITaskCancellableCommand`1.CanBeExecuted
  - Neutronium.BuildingBlocks.ApplicationTools.ITaskCancellableCommand`1.Cancel
  - Neutronium.BuildingBlocks.ApplicationTools.ITaskCancellableCommand`1.Computing
  - Neutronium.BuildingBlocks.ApplicationTools.ITaskCancellableCommand`1.Results
  - Neutronium.BuildingBlocks.ApplicationTools.ITaskCancellableCommand`1.Run
  langs:
  - csharp
  - vb
  name: ITaskCancellableCommand<TResult>
  nameWithType: ITaskCancellableCommand<TResult>
  fullName: Neutronium.BuildingBlocks.ApplicationTools.ITaskCancellableCommand<TResult>
  type: Interface
  source:
    remote:
      path: Neutronium.BuildingBlocks.ApplicationTools/ITaskCancellableCommand.cs
      branch: master
      repo: https://github.com/NeutroniumCore/Neutronium.BuildingBlocks.git
    id: ITaskCancellableCommand
    path: ../Neutronium.BuildingBlocks.ApplicationTools/ITaskCancellableCommand.cs
    startLine: 13
  assemblies:
  - Neutronium.BuildingBlocks.ApplicationTools
  namespace: Neutronium.BuildingBlocks.ApplicationTools
  summary: "\nCancellable command\n"
  example: []
  syntax:
    content: 'public interface ITaskCancellableCommand<TResult> : INotifyPropertyChanged, INotifyPropertyChanging'
    typeParameters:
    - id: TResult
      description: "\nResult type\n"
    content.vb: >-
      Public Interface ITaskCancellableCommand(Of TResult)
          Inherits INotifyPropertyChanged, INotifyPropertyChanging
  inheritedMembers:
  - System.ComponentModel.INotifyPropertyChanged.PropertyChanged
  - System.ComponentModel.INotifyPropertyChanging.PropertyChanging
  nameWithType.vb: ITaskCancellableCommand(Of TResult)
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
  fullName.vb: Neutronium.BuildingBlocks.ApplicationTools.ITaskCancellableCommand(Of TResult)
  name.vb: ITaskCancellableCommand(Of TResult)
- uid: Neutronium.BuildingBlocks.ApplicationTools.ITaskCancellableCommand`1.Computing
  commentId: P:Neutronium.BuildingBlocks.ApplicationTools.ITaskCancellableCommand`1.Computing
  id: Computing
  parent: Neutronium.BuildingBlocks.ApplicationTools.ITaskCancellableCommand`1
  langs:
  - csharp
  - vb
  name: Computing
  nameWithType: ITaskCancellableCommand<TResult>.Computing
  fullName: Neutronium.BuildingBlocks.ApplicationTools.ITaskCancellableCommand<TResult>.Computing
  type: Property
  source:
    remote:
      path: Neutronium.BuildingBlocks.ApplicationTools/ITaskCancellableCommand.cs
      branch: master
      repo: https://github.com/NeutroniumCore/Neutronium.BuildingBlocks.git
    id: Computing
    path: ../Neutronium.BuildingBlocks.ApplicationTools/ITaskCancellableCommand.cs
    startLine: 18
  assemblies:
  - Neutronium.BuildingBlocks.ApplicationTools
  namespace: Neutronium.BuildingBlocks.ApplicationTools
  summary: "\nTrue if the command is executing\n"
  example: []
  syntax:
    content: bool Computing { get; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: ReadOnly Property Computing As Boolean
  overload: Neutronium.BuildingBlocks.ApplicationTools.ITaskCancellableCommand`1.Computing*
  nameWithType.vb: ITaskCancellableCommand(Of TResult).Computing
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
  fullName.vb: Neutronium.BuildingBlocks.ApplicationTools.ITaskCancellableCommand(Of TResult).Computing
- uid: Neutronium.BuildingBlocks.ApplicationTools.ITaskCancellableCommand`1.CanBeExecuted
  commentId: P:Neutronium.BuildingBlocks.ApplicationTools.ITaskCancellableCommand`1.CanBeExecuted
  id: CanBeExecuted
  parent: Neutronium.BuildingBlocks.ApplicationTools.ITaskCancellableCommand`1
  langs:
  - csharp
  - vb
  name: CanBeExecuted
  nameWithType: ITaskCancellableCommand<TResult>.CanBeExecuted
  fullName: Neutronium.BuildingBlocks.ApplicationTools.ITaskCancellableCommand<TResult>.CanBeExecuted
  type: Property
  source:
    remote:
      path: Neutronium.BuildingBlocks.ApplicationTools/ITaskCancellableCommand.cs
      branch: master
      repo: https://github.com/NeutroniumCore/Neutronium.BuildingBlocks.git
    id: CanBeExecuted
    path: ../Neutronium.BuildingBlocks.ApplicationTools/ITaskCancellableCommand.cs
    startLine: 23
  assemblies:
  - Neutronium.BuildingBlocks.ApplicationTools
  namespace: Neutronium.BuildingBlocks.ApplicationTools
  summary: "\nTrue if the command can be executed\n"
  example: []
  syntax:
    content: bool CanBeExecuted { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Property CanBeExecuted As Boolean
  overload: Neutronium.BuildingBlocks.ApplicationTools.ITaskCancellableCommand`1.CanBeExecuted*
  nameWithType.vb: ITaskCancellableCommand(Of TResult).CanBeExecuted
  modifiers.csharp:
  - get
  - set
  fullName.vb: Neutronium.BuildingBlocks.ApplicationTools.ITaskCancellableCommand(Of TResult).CanBeExecuted
- uid: Neutronium.BuildingBlocks.ApplicationTools.ITaskCancellableCommand`1.Run
  commentId: P:Neutronium.BuildingBlocks.ApplicationTools.ITaskCancellableCommand`1.Run
  id: Run
  parent: Neutronium.BuildingBlocks.ApplicationTools.ITaskCancellableCommand`1
  langs:
  - csharp
  - vb
  name: Run
  nameWithType: ITaskCancellableCommand<TResult>.Run
  fullName: Neutronium.BuildingBlocks.ApplicationTools.ITaskCancellableCommand<TResult>.Run
  type: Property
  source:
    remote:
      path: Neutronium.BuildingBlocks.ApplicationTools/ITaskCancellableCommand.cs
      branch: master
      repo: https://github.com/NeutroniumCore/Neutronium.BuildingBlocks.git
    id: Run
    path: ../Neutronium.BuildingBlocks.ApplicationTools/ITaskCancellableCommand.cs
    startLine: 28
  assemblies:
  - Neutronium.BuildingBlocks.ApplicationTools
  namespace: Neutronium.BuildingBlocks.ApplicationTools
  summary: "\nExecute the command\n"
  example: []
  syntax:
    content: ICommand Run { get; }
    parameters: []
    return:
      type: System.Windows.Input.ICommand
    content.vb: ReadOnly Property Run As ICommand
  overload: Neutronium.BuildingBlocks.ApplicationTools.ITaskCancellableCommand`1.Run*
  nameWithType.vb: ITaskCancellableCommand(Of TResult).Run
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
  fullName.vb: Neutronium.BuildingBlocks.ApplicationTools.ITaskCancellableCommand(Of TResult).Run
- uid: Neutronium.BuildingBlocks.ApplicationTools.ITaskCancellableCommand`1.Cancel
  commentId: P:Neutronium.BuildingBlocks.ApplicationTools.ITaskCancellableCommand`1.Cancel
  id: Cancel
  parent: Neutronium.BuildingBlocks.ApplicationTools.ITaskCancellableCommand`1
  langs:
  - csharp
  - vb
  name: Cancel
  nameWithType: ITaskCancellableCommand<TResult>.Cancel
  fullName: Neutronium.BuildingBlocks.ApplicationTools.ITaskCancellableCommand<TResult>.Cancel
  type: Property
  source:
    remote:
      path: Neutronium.BuildingBlocks.ApplicationTools/ITaskCancellableCommand.cs
      branch: master
      repo: https://github.com/NeutroniumCore/Neutronium.BuildingBlocks.git
    id: Cancel
    path: ../Neutronium.BuildingBlocks.ApplicationTools/ITaskCancellableCommand.cs
    startLine: 33
  assemblies:
  - Neutronium.BuildingBlocks.ApplicationTools
  namespace: Neutronium.BuildingBlocks.ApplicationTools
  summary: "\nCancel the current execution\n"
  example: []
  syntax:
    content: ISimpleCommand Cancel { get; }
    parameters: []
    return:
      type: Neutronium.MVVMComponents.ISimpleCommand
    content.vb: ReadOnly Property Cancel As ISimpleCommand
  overload: Neutronium.BuildingBlocks.ApplicationTools.ITaskCancellableCommand`1.Cancel*
  nameWithType.vb: ITaskCancellableCommand(Of TResult).Cancel
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
  fullName.vb: Neutronium.BuildingBlocks.ApplicationTools.ITaskCancellableCommand(Of TResult).Cancel
- uid: Neutronium.BuildingBlocks.ApplicationTools.ITaskCancellableCommand`1.Results
  commentId: P:Neutronium.BuildingBlocks.ApplicationTools.ITaskCancellableCommand`1.Results
  id: Results
  parent: Neutronium.BuildingBlocks.ApplicationTools.ITaskCancellableCommand`1
  langs:
  - csharp
  - vb
  name: Results
  nameWithType: ITaskCancellableCommand<TResult>.Results
  fullName: Neutronium.BuildingBlocks.ApplicationTools.ITaskCancellableCommand<TResult>.Results
  type: Property
  source:
    remote:
      path: Neutronium.BuildingBlocks.ApplicationTools/ITaskCancellableCommand.cs
      branch: master
      repo: https://github.com/NeutroniumCore/Neutronium.BuildingBlocks.git
    id: Results
    path: ../Neutronium.BuildingBlocks.ApplicationTools/ITaskCancellableCommand.cs
    startLine: 38
  assemblies:
  - Neutronium.BuildingBlocks.ApplicationTools
  namespace: Neutronium.BuildingBlocks.ApplicationTools
  summary: "\nResults exposed as Observable <xref href=\"Neutronium.BuildingBlocks.ApplicationTools.CommandResult%601\" data-throw-if-not-resolved=\"false\"></xref>\n"
  example: []
  syntax:
    content: IObservable<CommandResult<TResult>> Results { get; }
    parameters: []
    return:
      type: System.IObservable{Neutronium.BuildingBlocks.ApplicationTools.CommandResult{{TResult}}}
    content.vb: ReadOnly Property Results As IObservable(Of CommandResult(Of TResult))
  overload: Neutronium.BuildingBlocks.ApplicationTools.ITaskCancellableCommand`1.Results*
  nameWithType.vb: ITaskCancellableCommand(Of TResult).Results
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
  fullName.vb: Neutronium.BuildingBlocks.ApplicationTools.ITaskCancellableCommand(Of TResult).Results
references:
- uid: Neutronium.BuildingBlocks.ApplicationTools
  commentId: N:Neutronium.BuildingBlocks.ApplicationTools
  name: Neutronium.BuildingBlocks.ApplicationTools
  nameWithType: Neutronium.BuildingBlocks.ApplicationTools
  fullName: Neutronium.BuildingBlocks.ApplicationTools
- uid: System.ComponentModel.INotifyPropertyChanged.PropertyChanged
  commentId: E:System.ComponentModel.INotifyPropertyChanged.PropertyChanged
  parent: System.ComponentModel.INotifyPropertyChanged
  isExternal: true
  name: PropertyChanged
  nameWithType: INotifyPropertyChanged.PropertyChanged
  fullName: System.ComponentModel.INotifyPropertyChanged.PropertyChanged
- uid: System.ComponentModel.INotifyPropertyChanging.PropertyChanging
  commentId: E:System.ComponentModel.INotifyPropertyChanging.PropertyChanging
  parent: System.ComponentModel.INotifyPropertyChanging
  isExternal: true
  name: PropertyChanging
  nameWithType: INotifyPropertyChanging.PropertyChanging
  fullName: System.ComponentModel.INotifyPropertyChanging.PropertyChanging
- uid: System.ComponentModel.INotifyPropertyChanged
  commentId: T:System.ComponentModel.INotifyPropertyChanged
  parent: System.ComponentModel
  isExternal: true
  name: INotifyPropertyChanged
  nameWithType: INotifyPropertyChanged
  fullName: System.ComponentModel.INotifyPropertyChanged
- uid: System.ComponentModel.INotifyPropertyChanging
  commentId: T:System.ComponentModel.INotifyPropertyChanging
  parent: System.ComponentModel
  isExternal: true
  name: INotifyPropertyChanging
  nameWithType: INotifyPropertyChanging
  fullName: System.ComponentModel.INotifyPropertyChanging
- uid: System.ComponentModel
  commentId: N:System.ComponentModel
  isExternal: true
  name: System.ComponentModel
  nameWithType: System.ComponentModel
  fullName: System.ComponentModel
- uid: Neutronium.BuildingBlocks.ApplicationTools.ITaskCancellableCommand`1.Computing*
  commentId: Overload:Neutronium.BuildingBlocks.ApplicationTools.ITaskCancellableCommand`1.Computing
  name: Computing
  nameWithType: ITaskCancellableCommand<TResult>.Computing
  fullName: Neutronium.BuildingBlocks.ApplicationTools.ITaskCancellableCommand<TResult>.Computing
  nameWithType.vb: ITaskCancellableCommand(Of TResult).Computing
  fullName.vb: Neutronium.BuildingBlocks.ApplicationTools.ITaskCancellableCommand(Of TResult).Computing
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Neutronium.BuildingBlocks.ApplicationTools.ITaskCancellableCommand`1.CanBeExecuted*
  commentId: Overload:Neutronium.BuildingBlocks.ApplicationTools.ITaskCancellableCommand`1.CanBeExecuted
  name: CanBeExecuted
  nameWithType: ITaskCancellableCommand<TResult>.CanBeExecuted
  fullName: Neutronium.BuildingBlocks.ApplicationTools.ITaskCancellableCommand<TResult>.CanBeExecuted
  nameWithType.vb: ITaskCancellableCommand(Of TResult).CanBeExecuted
  fullName.vb: Neutronium.BuildingBlocks.ApplicationTools.ITaskCancellableCommand(Of TResult).CanBeExecuted
- uid: Neutronium.BuildingBlocks.ApplicationTools.ITaskCancellableCommand`1.Run*
  commentId: Overload:Neutronium.BuildingBlocks.ApplicationTools.ITaskCancellableCommand`1.Run
  name: Run
  nameWithType: ITaskCancellableCommand<TResult>.Run
  fullName: Neutronium.BuildingBlocks.ApplicationTools.ITaskCancellableCommand<TResult>.Run
  nameWithType.vb: ITaskCancellableCommand(Of TResult).Run
  fullName.vb: Neutronium.BuildingBlocks.ApplicationTools.ITaskCancellableCommand(Of TResult).Run
- uid: System.Windows.Input.ICommand
  commentId: T:System.Windows.Input.ICommand
  parent: System.Windows.Input
  isExternal: true
  name: ICommand
  nameWithType: ICommand
  fullName: System.Windows.Input.ICommand
- uid: System.Windows.Input
  commentId: N:System.Windows.Input
  isExternal: true
  name: System.Windows.Input
  nameWithType: System.Windows.Input
  fullName: System.Windows.Input
- uid: Neutronium.BuildingBlocks.ApplicationTools.ITaskCancellableCommand`1.Cancel*
  commentId: Overload:Neutronium.BuildingBlocks.ApplicationTools.ITaskCancellableCommand`1.Cancel
  name: Cancel
  nameWithType: ITaskCancellableCommand<TResult>.Cancel
  fullName: Neutronium.BuildingBlocks.ApplicationTools.ITaskCancellableCommand<TResult>.Cancel
  nameWithType.vb: ITaskCancellableCommand(Of TResult).Cancel
  fullName.vb: Neutronium.BuildingBlocks.ApplicationTools.ITaskCancellableCommand(Of TResult).Cancel
- uid: Neutronium.MVVMComponents.ISimpleCommand
  commentId: T:Neutronium.MVVMComponents.ISimpleCommand
  parent: Neutronium.MVVMComponents
  isExternal: true
  name: ISimpleCommand
  nameWithType: ISimpleCommand
  fullName: Neutronium.MVVMComponents.ISimpleCommand
- uid: Neutronium.MVVMComponents
  commentId: N:Neutronium.MVVMComponents
  isExternal: true
  name: Neutronium.MVVMComponents
  nameWithType: Neutronium.MVVMComponents
  fullName: Neutronium.MVVMComponents
- uid: Neutronium.BuildingBlocks.ApplicationTools.CommandResult`1
  commentId: T:Neutronium.BuildingBlocks.ApplicationTools.CommandResult`1
  name: CommandResult<TResult>
  nameWithType: CommandResult<TResult>
  fullName: Neutronium.BuildingBlocks.ApplicationTools.CommandResult<TResult>
  nameWithType.vb: CommandResult(Of TResult)
  fullName.vb: Neutronium.BuildingBlocks.ApplicationTools.CommandResult(Of TResult)
  name.vb: CommandResult(Of TResult)
  spec.csharp:
  - uid: Neutronium.BuildingBlocks.ApplicationTools.CommandResult`1
    name: CommandResult
    nameWithType: CommandResult
    fullName: Neutronium.BuildingBlocks.ApplicationTools.CommandResult
  - name: <
    nameWithType: <
    fullName: <
  - name: TResult
    nameWithType: TResult
    fullName: TResult
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Neutronium.BuildingBlocks.ApplicationTools.CommandResult`1
    name: CommandResult
    nameWithType: CommandResult
    fullName: Neutronium.BuildingBlocks.ApplicationTools.CommandResult
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TResult
    nameWithType: TResult
    fullName: TResult
  - name: )
    nameWithType: )
    fullName: )
- uid: Neutronium.BuildingBlocks.ApplicationTools.ITaskCancellableCommand`1.Results*
  commentId: Overload:Neutronium.BuildingBlocks.ApplicationTools.ITaskCancellableCommand`1.Results
  name: Results
  nameWithType: ITaskCancellableCommand<TResult>.Results
  fullName: Neutronium.BuildingBlocks.ApplicationTools.ITaskCancellableCommand<TResult>.Results
  nameWithType.vb: ITaskCancellableCommand(Of TResult).Results
  fullName.vb: Neutronium.BuildingBlocks.ApplicationTools.ITaskCancellableCommand(Of TResult).Results
- uid: System.IObservable{Neutronium.BuildingBlocks.ApplicationTools.CommandResult{{TResult}}}
  commentId: T:System.IObservable{Neutronium.BuildingBlocks.ApplicationTools.CommandResult{`0}}
  parent: System
  definition: System.IObservable`1
  name: IObservable<CommandResult<TResult>>
  nameWithType: IObservable<CommandResult<TResult>>
  fullName: System.IObservable<Neutronium.BuildingBlocks.ApplicationTools.CommandResult<TResult>>
  nameWithType.vb: IObservable(Of CommandResult(Of TResult))
  fullName.vb: System.IObservable(Of Neutronium.BuildingBlocks.ApplicationTools.CommandResult(Of TResult))
  name.vb: IObservable(Of CommandResult(Of TResult))
  spec.csharp:
  - uid: System.IObservable`1
    name: IObservable
    nameWithType: IObservable
    fullName: System.IObservable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: Neutronium.BuildingBlocks.ApplicationTools.CommandResult`1
    name: CommandResult
    nameWithType: CommandResult
    fullName: Neutronium.BuildingBlocks.ApplicationTools.CommandResult
  - name: <
    nameWithType: <
    fullName: <
  - name: TResult
    nameWithType: TResult
    fullName: TResult
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.IObservable`1
    name: IObservable
    nameWithType: IObservable
    fullName: System.IObservable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: Neutronium.BuildingBlocks.ApplicationTools.CommandResult`1
    name: CommandResult
    nameWithType: CommandResult
    fullName: Neutronium.BuildingBlocks.ApplicationTools.CommandResult
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TResult
    nameWithType: TResult
    fullName: TResult
  - name: )
    nameWithType: )
    fullName: )
  - name: )
    nameWithType: )
    fullName: )
- uid: System.IObservable`1
  commentId: T:System.IObservable`1
  isExternal: true
  name: IObservable<T>
  nameWithType: IObservable<T>
  fullName: System.IObservable<T>
  nameWithType.vb: IObservable(Of T)
  fullName.vb: System.IObservable(Of T)
  name.vb: IObservable(Of T)
  spec.csharp:
  - uid: System.IObservable`1
    name: IObservable
    nameWithType: IObservable
    fullName: System.IObservable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.IObservable`1
    name: IObservable
    nameWithType: IObservable
    fullName: System.IObservable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
